DATA:
  data_root: '/home/barcellona/workspace/git_repo/ASGNet/custom_inference/'
  train_list: '/home/barcellona/workspace/git_repo/ASGNet/custom_inference/list/graspnet_train_small.txt'
  val_list: '/home/barcellona/workspace/git_repo/ASGNet/custom_inference/list/graspnet_val_small.txt'
  class_list:  '/home/barcellona/workspace/git_repo/ASGNet/custom_inference/list/graspnet_classes.txt'
  classes: 2

TRAIN:
  arch: asgnet
  layers: 50 # 50 or 101
  sync_bn: False
  train_h: 721 #481 #641 #SIZE 720
  train_w: 1281 #361 #641 #SIZE 1280
  val_size: 721 #481 #641
  scale_min: 0.8  # minimum random scale
  scale_max: 1.25 # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  padding_label: 255
  aux_weight: 1.0
  train_gpu: [0]
  workers: 16  # data loader workers
  batch_size: 8  # batch size for training.
  batch_size_val: 1 # this version of code only support val batch = 1
  base_lr: 0.005
  epochs: 15
  start_epoch: 0
  power: 0.9 # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 321
  print_freq: 5
  save_freq: 1
  save_path: exp/asgnet/graspnet/split0_resnet50/model
  weight: /home/barcellona/workspace/git_repo/ASGNet/coco/s2_5s_resnet50.pth
  resume:
  evaluate: True
  split: 0
  shot: 5
  max_sp: 5
  train_iter: 10
  eval_iter: 5
  pyramid: True
  ppm_scales: [1.0, 0.5, 0.25, 0.125]
  fix_random_seed_val: True
  warmup: False
  use_coco: False
  use_split_coco: True
  resized_val: True
  ori_resize: True  # use original label for evaluation
  vgg: False

## deprecated multi-processing training
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0
  use_apex: False
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:



